[tool.poetry]
name = "django-erd"
version = "0.1.0"
description = "Django ERD Generator is a command-line tool designed to generate Entity-Relationship Diagrams (ERDs) from Django models. It supports multiple output formats, making it easy to visualise database relationships in different diagramming tools. The generator extracts model definitions, fields, and relationships, converting them into structured representations suitable for use with Mermaid.js, PlantUML, and dbdiagram.io. This tool is useful for understanding database structures, documenting data models, and sharing visual representations with team members."
authors = ["Andryo Marzuki <andryo@mrzk.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.2"

[tool.poetry.group.dev.dependencies]
tox = "^4.24.1"
pytest = "^8.3.4"
pytest-django = "^4.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
